### PR TITLE
Revert incompatible changes in #1193 and additional improvements

### LINKED ISSUE #1210: Connecting to broker now blocks forever by default
After #1193 several methods started to block connection to broker till is not established. This can take forever when  broker won't appear. Moreover, it changed raised exceptions to OperationalError instead of native transport one. It seems that this change affects users  - see: #429 

The semantics of this should be at least postponed an introduced properly after proper discussion.

### PR DESCRIPTION
**Pull request by matusvalo**
Fixes #1210

### CODE REVIEW

**Comment by auvipy** [comment]
ping me when ready for review

**Comment by auvipy** [comment]
2 integration tests were failing

**Comment by auvipy** [comment]
would be great if you could complete this by this week

**Comment by matusvalo** [comment]
@auvipy I am ready. There is failing just apicheck due new release of botocore.

**Comment by matusvalo** [comment]
I have extended tests. Moreover I have verified them against older version of kombu and they are passing so the API should be compatible.

**Pull request merged**
