### PR TITLE
Fix libSystem.dylib import on OS X 10.11

### PR DESCRIPTION
**Pull request by ewang**
PR for #521 

This will also need to be ported in py-amqp eventually since the master simply inherits from amqp.five

### CODE REVIEW

**Comment by ask** [comment]
Thanks!

Weirdly, this is not an issue for me on my 10.11 installation, but maybe I have a slightly different environment or something, deployment target or whatever.

**Comment by ask** [comment]
Merged into kombu 3.0, pyamqp master+1.4, billiard master,3.3

**Comment by ewang** [comment]
Do you think you would be able to do a  release on pypi that includes just this change?

I already saw an article on stackoverflow w/ this same issue and I imagine more will start encountering it.


Thanks!

**Comment by sideboltconor** [comment]
Also wondering if there is an eta on this update. A number of our developers ran into this issue when upgrading to 10.11.

Much appreciated!

**Comment by ask** [comment]
Kombu 3.0.27 was released on  2015-10-09 :)

**Pull request closed without merging**
