### PR TITLE
[WIP] Drop Python 2: Removal of Python 2 specific codes

### PR DESCRIPTION
**Pull request by auvipy**
Will merge after 4.3 release. work in progress!

### CODE REVIEW

**Comment by atombrella** [comment]
There are some remnants in `kombu/__init__.py`, see `2.5 does not define __package__`. A trivial one is also in `introduction.txt` (`print body` should be `print(body)`.

**Comment by auvipy** [comment]
thank you. will complete before the release of v5

**Comment by auvipy** [comment]
@thedrow you can focus on kombu 5 branch for this. for kombu 4.7 onwards 4.8, 4.9, etc the existing users won't get python2 support anymore but the other functionalities will remain to keep BC compat as much as possible with the gradual adaptation of new features which are less destructive for existing large codebases.

**Comment by thedrow** [comment]
Where exactly can I pull this from?

**Pull request closed without merging**
