### PR TITLE
Drop Python 2 Support

### PR DESCRIPTION
**Pull request by thedrow**
We now drop Python 2 support in Kombu as well.

After this is merged we must enter a merge freeze period.

Supersedes #990.

### CODE REVIEW

**Comment by auvipy** [comment]
what about another branch? say v5 like celery?

**Comment by thedrow** [comment]
> what about another branch? say v5 like celery?

Since we're going to drop support for Python 2 soon I don't think it is needed.
We can maintain Kombu 4.x in a release branch.
What do you think?

**Comment by auvipy** [comment]
> > what about another branch? say v5 like celery?
> 
> Since we're going to drop support for Python 2 soon I don't think it is needed.
> We can maintain Kombu 4.x in a release branch.
> What do you think?

a maintenance branch before merging this is fair enough. it would be good to hold this merge for this week. I will be in vacation throughout this week. didn't have any vacation or break from the last march Corona lockdown.

**Comment by thedrow** [comment]
> > > what about another branch? say v5 like celery?
> > 
> > Since we're going to drop support for Python 2 soon I don't think it is needed.
> > We can maintain Kombu 4.x in a release branch.
> > What do you think?
> 
> a maintenance branch before merging this is fair enough. it would be good to hold this merge for this week. I will be in vacation throughout this week. didn't have any vacation or break from the last march Corona lockdown.

I'm not sure I can hold off the release but I can guarantee I'll be responsible and will regularly check the repositories for new issues.

Have fun during your vacation.

**Comment by matusvalo** [comment]
Unfortunately, I don't have much time to review this PR. I will do it after next week.

**Comment by thedrow** [comment]
@matusvalo I think it's fine and we can still release this.

**Pull request merged**
