### PR TITLE
respect connection timeout

### PR DESCRIPTION
**Pull request by mehdipourfar**
Consider the following code which has been copied from the README file, except that I have added `transport_options={'max_retries': 3}` and `connect_timeout=1` as parameters to Connection.

```python
from kombu import Connection, Exchange, Queue

media_exchange = Exchange('media', 'direct', durable=True)
video_queue = Queue('video', exchange=media_exchange, routing_key='video')


# connections
with Connection('amqp://guest:guest@localhost//',
                transport_options={'max_retries': 3},
                connect_timeout=1) as conn:
    # produce
    producer = conn.Producer(serializer='json')
    producer.publish({'name': '/tmp/lolcat1.avi', 'size': 1301013},
                     exchange=media_exchange, routing_key='video',
                     declare=[video_queue])
```

As it appears, this script should take 3 seconds to fail when rabbitmq is down, but with the current version of Kombu, it hangs forever. Also when I try to publish a celery task when rabbitmq is down, the same thing happens.  This commit fixes this problem which have been resided in Kombu for at least two years as far as I know.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
OK cool, can you also add the parts you added on PR description to docs, and add simple unit test as well?

**Comment by mehdipourfar** [comment]
> OK cool, can you also add the parts you added on PR description to docs, and add simple unit test as well?

I've added a test but there is nothing to add to the docs. It's already been mentioned [here](https://docs.celeryproject.org/projects/kombu/en/stable/reference/kombu.connection.html#kombu.connection.Connection.connect_timeout) but it was buggy.

**Review by auvipy — CHANGES_REQUESTED** [review]
thanks for the unit test which are passing. but the integration tests are failing, which might need some adjustment, can you please have a look?

**Comment by mehdipourfar** [comment]
> thanks for the unit test which are passing. but the integration tests are failing, which might need some adjustment, can you please have a look?

I've tried to check them on my own laptop. They will also fail with the same error on master branch. Could you investigate it?

**Comment by auvipy** [comment]
I will try to have a look tomorrow

**Review by matusvalo — CHANGES_REQUESTED** [review]
Integration tests are failing.

**Comment by matusvalo** [comment]
I will try to have a look to this PR.

**Comment by auvipy** [comment]
probably related to https://github.com/celery/py-amqp/pull/379, let see after new release

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please pull from master and run tests again

**Comment by mehdipourfar** [comment]
> can you please pull from master and run tests again

I've merged it with master. Now the integration tests are passing but unit tests are failing with the error `error: unrecognized arguments: --cov=kombu --cov-report=xml --no-cov-on-fail`. 
Maybe something is wrong with my development environment. Could you run the workflows to see if they also fail on CI?

**Comment by auvipy** [comment]
I restarted the CI

**Comment by mehdipourfar** [comment]
> I restarted the CI

Thanks. It seems that now everything works as expected.

**Review by auvipy — APPROVED** [review]
it does. the integration failures were due to regression in py-amqp release which is fixed in latest pypi release

**Comment by auvipy** [comment]
thanks a lot for your contribution

**Pull request merged**
