### PR TITLE
test amqp v5.0.9

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by auvipy** [comment]
@pawl @michael-lazar can you guys please investigate the kombu integration test failures?

**Comment by avi-city** [comment]
Hi all,
Is it possible to change to `amqp==5.0.7` in the meanwhile?
My package is depended on kombu and it currently breaks it.

Thanks,
Avi

**Comment by auvipy** [comment]
ofcourse, you should pin your amqp, kombu hasn't released any version with 5.0.8 yet.

**Comment by pawl** [comment]
@auvipy This should fix those integration test failures: https://github.com/celery/py-amqp/pull/383

**Comment by auvipy** [comment]
OK lets see

**Comment by auvipy** [comment]
ok this is another type of issue in CI ================================== log start ===================================
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    scheme['data'] = scheme['purelib']
KeyError: 'purelib'

**Comment by auvipy** [comment]
the failure is probably setuptools new release

**Pull request merged**
