### PR TITLE
Fix redis health checks

### PR DESCRIPTION
**Pull request by Ashish-Bansal**
#### Description 

Fixes https://github.com/celery/kombu/issues/1019

https://github.com/celery/kombu/pull/1113 didn't set `health_check_interval` parameter due to which calling health_check on the underlying redis client become no-op.

#### Testing

I have tested this branch on my setup and seems to work fine, I'm able to receive `"PING" "redis-py-health-check"` messages in redis monitor. 

Though I haven't tested `SentinelChannel`. As far as I can see, it won't work on Sentinel but at least won't be crashing it out. I don't plan to add support for Sentinel since I won't be able to test it out.

Other than that, I have handled it for both newer as well as older redis python clients.

### CODE REVIEW

**Comment by auvipy** [comment]
python 3 tests are faiing

**Comment by Ashish-Bansal** [comment]
@auvipy Please review this PR, thanks!

**Comment by deepchatterjeeligo** [comment]
I tried installing celery from master (https://github.com/celery/celery.git) and kombu from #1122 (https://github.com/LeetCode-OpenSource/kombu.git) and can confirm that a minimal check like that mentioned [here](https://github.com/celery/kombu/pull/1117#issuecomment-552108492) does not throw an exception.

**Comment by Ashish-Bansal** [comment]
> if you have time, can you also add some integration tests?

Hm, I'll try to look into integration tests this weekend.

**Comment by auvipy** [comment]
any update on integration tests?

**Comment by Ashish-Bansal** [comment]
> any update on integration tests?

I did check up integration tests some time ago but there was more amount of work needed on that.

**Pull request merged**
