### PR TITLE
4.3 Changelog

### PR DESCRIPTION
**Pull request by thedrow**
This is still work in progress but I'm nearly done.
I need to take another pass at the commit log, detail some of the changes and ensure all tests, cleanups and documentation contributions are attributed.

Please take a look and see if something is missing or incorrect.

### CODE REVIEW

**Comment by clokep** [comment]
@thedrow Won't help you now, but would it make sense to try to include changelog updates in each PR instead of collecting them for each release?

**Comment by thedrow** [comment]
I've been thinking about migrating to https://github.com/openstack/reno or a similar tool.

**Comment by clokep** [comment]
Awesome! That sounds a lot like what Twisted does:
* https://github.com/twisted/twisted/blob/6ac66416c0238f403a8dc1d42924fb3ba2a2a686/docs/core/development/policy/release-process.rst#how-to-do-a-release-candidate
* https://pypi.org/project/towncrier/

**Comment by matusvalo** [comment]
@thedrow great work. Is #916 also part of release? I don't see it in changelog. Otherwise, PR is OK for me.

**Comment by matusvalo** [comment]
Regarding the changelog, maybe the most simple way is to add as part of PR to update the changelog. More projects require it - e.g. pylint: http://pylint.pycqa.org/en/latest/development_guide/contribute.html#repository

**Comment by thedrow** [comment]
@matusvalu good catch. I'll see if it's included.
I'd rather limit our contribution friction.
Let's discuss it elsewhere. I don't want everyone to be pinged if it's not a relevant part of the PR.

**Comment by auvipy** [comment]
excellent work!! thank you!!

**Pull request merged**
