### PR TITLE
Limit requests<2.32.0 due to docker-py issue 3256

### PR DESCRIPTION
**Pull request by Nusnus**
Extracted from https://github.com/celery/kombu/pull/2007 by @awmackowiak

Due to: https://github.com/docker/docker-py/issues/3256

### CODE REVIEW

**Comment by Nusnus** [comment]
Don’t tell me it breaks due to new rabbitmq image now 🤦‍♂️

**Comment by Nusnus** [comment]
> Don’t tell me it breaks due to new rabbitmq image now 🤦‍♂️

Trying to limit requests and rabbitmq image separately: https://github.com/celery/kombu/pull/2012

If it won’t work, it might need to be done in the same PR.

**Comment by Nusnus** [comment]
> > Don’t tell me it breaks due to new rabbitmq image now 🤦‍♂️
> 
> Trying to limit requests and rabbitmq image separately: #2012
> 
> If it won’t work, it might need to be done in the same PR.

Ok it didn’t work. Trying to do both in a single PR.

**Comment by Nusnus** [comment]
> > > Don’t tell me it breaks due to new rabbitmq image now 🤦‍♂️
> > 
> > 
> > Trying to limit requests and rabbitmq image separately: #2012
> > If it won’t work, it might need to be done in the same PR.
> 
> Ok it didn’t work. Trying to do both in a single PR.

Reverted the rabbitmq limit and added the tox.ini changes from the #2007 PR (forgot to add it in the first place)

**Comment by awmackowiak** [comment]
@Nusnus I also tried to find a silver bullet for those dependency cycle versions... and I also failed. 
I also agree that is a messy problem which generates serious tech dept :(
But I think is a fresh case so maybe quickly those dependent libraries will update requests as well as everybody does.

**Comment by max-wittig** [comment]
I was about to test https://github.com/celery/kombu/releases/tag/v5.4.0rc1, but sadly this prevents it as I don't feel like downgrading requests as 2.32.0 contains security fixes. To my understanding (maybe I'm wrong), requests was only downgraded to make sure that tests still work, right?

Couldn't this be just downgraded for the tests?

**Comment by Nusnus** [comment]
> Couldn't this be just downgraded for the tests?

Yes, and it was already changed accordingly yesterday 🙂
https://github.com/celery/kombu/pull/2041

**Comment by max-wittig** [comment]
@Nusnus Ahh okay! Sorry I've not seen that! So I will test the next pre-release 🙂  Thanks!

**Comment by Nusnus** [comment]
@max-wittig 
> @Nusnus Ahh okay! Sorry I've not seen that! So I will test the next pre-release 🙂 Thanks!

[v5.4.0rc2](https://github.com/celery/kombu/releases/tag/v5.4.0rc2) is out!
The `requests` package is no longer limited to <2.32.0 per https://github.com/celery/kombu/pull/2041.

**Pull request merged**
