### PR TITLE
Fix resizing and expose option for celery to forcibly resize

### PR DESCRIPTION
**Pull request by hp685**
It pops from the self._resource.queue but does not collect the resource when shrinking down

### CODE REVIEW

**Comment by hp685** [comment]
1.Provide and expose option to forcibly set the limit.
2. Fix pool resizing when incrementing pool from default value. 

This can now be called from within celery's Celery() object. Need a corresponding PR for celery

**Comment by hp685** [comment]
@auvipy Should I raise the PR for celery in tandem? That PR will have a dependency on this PR.

**Comment by auvipy** [comment]
/home/travis/build/celery/kombu/kombu/transport/redis.py:1110:60: E231 missing whitespace after ','
/home/travis/build/celery/kombu/t/unit/transport/test_redis.py:1347:80: E501 line too long (103 > 79 characters)
/home/travis/build/celery/kombu/t/unit/transport/test_redis.py:1355:80: E501 line too long (95 > 79 characters)

**Comment by hp685** [comment]
These failures stem from a different changeset but I've gone ahead and addressed them as they are syntactical. Looks like master is failing. My forked master passes that test fine.

**Comment by auvipy** [comment]
restarted the build for check

**Comment by hp685** [comment]
Created another PR with fresh pull from master

**Pull request closed without merging**
