### PR TITLE
Fixed ValueError caused by mongodb rc version: invalid literal for in…

### PR DESCRIPTION
**Pull request by dust8**
when mongodb version is like '3.6.0-rc1-45-gdb64381', will raise ValueError: invalid literal for int() with base 10.

### CODE REVIEW

**Comment by dust8** [comment]
The error is not caused by my patch.

**Comment by auvipy** [comment]
I have few questions though, should celery really care about rc of any tranport/backend? after the stable version what will be the usefulness of the patch?

**Comment by dust8** [comment]
May be not  useful to most people, but friendly to novices

**Comment by dust8** [comment]
1.pypy:The command "pip install -U tox" failed 3 times.

2.flake8:flake8 runtests: PYTHONHASHSEED='2541432374'
flake8 runtests: commands[0] | flake8 /home/travis/build/celery/kombu/kombu /home/travis/build/celery/kombu/t
  /home/travis/build/celery/kombu$ /home/travis/build/celery/kombu/.tox/flake8/bin/flake8 /home/travis/build/celery/kombu/kombu /home/travis/build/celery/kombu/t 
/home/travis/build/celery/kombu/kombu/transport/SLMQ.py:122:9: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/kombu/transport/SLMQ.py:127:13: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/kombu/utils/debug.py:18:9: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/t/unit/test_log.py:21:9: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/t/unit/test_log.py:28:9: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/t/unit/test_log.py:33:9: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/t/unit/test_log.py:37:9: E741 ambiguous variable name 'l'
/home/travis/build/celery/kombu/t/unit/utils/test_encoding.py:100:15: E742 ambiguous class definition 'O'
ERROR: InvocationError: '/home/travis/build/celery/kombu/.tox/flake8/bin/flake8 /home/travis/build/celery/kombu/kombu /home/travis/build/celery/kombu/t'
___________________________________ summary ____________________________________
ERROR:   flake8: commands failed

3.apicheck:reading sources... [  1%] changelog
/home/travis/build/celery/kombu/.tox/apicheck/lib/python2.7/site-packages/sphinx/environment/__init__.py:686: RemovedInSphinx17Warning: html_use_smartypants option is deprecated. Smart quotes are on by default; if you want to disable or customize them, use the smart_quotes option in docutils.conf.
  RemovedInSphinx17Warning)
Exception occurred:
  File "/home/travis/build/celery/kombu/.tox/apicheck/lib/python2.7/site-packages/docutils/nodes.py", line 567, in __getitem__
    return self.attributes[key]
KeyError: 'refdomain'
The full traceback has been saved in /tmp/sphinx-err-G98xgn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ERROR: InvocationError: '/home/travis/build/celery/kombu/.tox/apicheck/bin/sphinx-build -b apicheck -d /home/travis/build/celery/kombu/.tox/apicheck/tmp/doctrees docs docs/_build/apicheck'
___________________________________ summary ____________________________________
ERROR:   apicheck: commands failed


I donot how to fix it.Can you help me？

**Comment by thedrow** [comment]
I just fixed the build problems today :)
Feel free to rebase.

I think we will merge this once we'll be able to test the patch using a GA version of MongoDB.

**Pull request merged**
