### PR TITLE
Control pattern matching

### PR DESCRIPTION
**Pull request by jheld**
rebase and small adjustments for matching logic based on #377

### CODE REVIEW

**Comment by thedrow** [comment]
Sorry. I mentioned the wrong issue.

**Comment by thedrow** [comment]
The MatcherNotInstalled class should be documented.

**Comment by jheld** [comment]
@thedrow not sure what else.

**Comment by thedrow** [comment]
See https://travis-ci.org/celery/kombu/jobs/489290777#L614
The module should have a docstring.

**Comment by jheld** [comment]
@thedrow I'm confused. I do have a module docstring on the first line. Where do you see it saying that I don't?

**Comment by thedrow** [comment]
Please allow me to push to your branch. See https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork
The problem is that this new module is not included in docs/reference.
I've added them but I can't push to your branch.

**Comment by jheld** [comment]
Thank you. Please repull/reset hard. I squashed back down to 2 commits.

**Comment by thedrow** [comment]
Ok so the only thing that's missing is test coverage and this PR is good to go.

**Comment by jheld** [comment]
I'm happy to add additional tests. Is there a specific spot or test coverage you're trying to hit?

**Pull request merged**
