### PR TITLE
［Fix］celery's mailbox queue name is not meet with beanstalk tube format.

### PR DESCRIPTION
**Pull request by fatelei**
Celery generate queue name `celery@laptop.celery.pidbox` is [invalid](https://github.com/kr/beanstalkd/blob/5fce2d1e14b61b0ffcb5d67f85f35792f8542d60/prot.c#L21) for beanstalkd. This pr replaces `@` to `.` to meet with the standards of beanstalkd.

### CODE REVIEW

**Comment by thedrow** [comment]
Is it possible to add a test for this?

**Comment by fatelei** [comment]
ok, i will add a test.

**Comment by fatelei** [comment]
@thedrow I have already add related tests.

**Comment by thedrow** [comment]
Thanks.

**Pull request merged**
