### PR TITLE
Allowing `Connection.ensure()` to retry on specific exceptions given by policy

### PR DESCRIPTION
**Pull request by Nusnus**
To be used with [task_publish_retry_policy](https://github.com/celery/celery/blob/7b585138af8318d62b8fe7086df7e85d110ac786/celery/app/defaults.py#L270)

### CODE REVIEW

**Comment by Nusnus** [comment]
The PR is in draft because I want to make some manual tests first for this change, if they passes I'll move this to "Ready for Review"

**Comment by Nusnus** [comment]
@auvipy Do we have any lead on the redis auth errors?

**Comment by auvipy** [comment]
that might be for new redis server / library release issue. have to check. allow me till saturday. I have to adjust/update CI of both kombu and py-amqp and packaging

**Comment by Nusnus** [comment]
Yeah I noticed the update to redis. Thanks for taking care of that!

**Review by thedrow — APPROVED** [review]

**Comment by auvipy** [comment]
It was eventually reverted

**Pull request merged**
