### PR TITLE
Added redis transport key_prefix from envvars

### PR DESCRIPTION
**Pull request by attiasr**

### CODE REVIEW

**Comment by auvipy** [comment]
which issue you are trying to fix? can you add a test?

**Comment by attiasr** [comment]
sorry for the late reply but I see you've already approved it, closed it and reopen so I'll explain;

This PRs will allow you to namespace different celery installation running against the same redis instance

**Comment by matusvalo** [comment]
Is there any need of this patch? All key names  can be modified via transport options:

https://github.com/celery/kombu/blob/a042d57c575092ab131d2609d1d9523991d42e34/kombu/transport/redis.py#L477-L498

Moreover this PR is missing unittests and documentation. I prefer to revert this PR and rethink it if it is needed or not.

**Comment by thedrow** [comment]
@matusvalo Can you take care of that?

**Comment by matusvalo** [comment]
Yes if there is agreement on it, I will revert it.

**Comment by matusvalo** [comment]
@attiasr we have reverted the change. If you still need prefixing functionality, we can discuss about it. Please create a new bug and we can drive discussion there.

**Pull request merged**
