### PR TITLE
Fix issue #789: Async http code not allowing for proxy config

### LINKED ISSUE #789: No proxy support using SQS
The async HTTP code is not allowing the proxy environment variables to be used by libcurl

It seems to be due to this code in `async/http/curl.py`

```
        if request.proxy_host:
            if not request.proxy_port:
                raise ValueError('Request with proxy_host but no proxy_port')
            setopt(_pycurl.PROXY, request.proxy_host)
            setopt(_pycurl.PROXYPORT, request.proxy_port)
            if request.proxy_username:
                setopt(_pycurl.PROXYUSERPWD, '{0}:{1}'.format(
                    request.proxy_username, request.proxy_password or ''))
        else:
            setopt(_pycurl.PROXY, '')
            curl.unsetopt(_pycurl.PROXYUSERPWD)
```
Notice that if the original request does not specify a `proxy_host` then it actually sets it to empty in the curl OPTs which makes libcurl NOT read the environment for it either.

And the caller in this case is the SQS transport which does NOT pass any proxy setting in either so when using SQS there doesn't appear to be a way to make Kombu use a proxy for the async HTTP. 

(Note: The calls through Boto DO work because Boto reads it from the environment variables by default)

### PR DESCRIPTION
**Pull request by jkoehl**
Fixes #789  

Don't reset the proxy config in the async curl based http request building unless that is specified by the caller

### CODE REVIEW

**Comment by jkoehl** [comment]
In theory if someone had setup their environment to use a proxy and this code used to ignore that and bypass the proxy. They may have had a reason they wanted to bypass the proxy for Celery but use a proxy for other things but this behavior is kind of not obvious.

For anyone actually needing to use a proxy to get to the queue this change is needed. In my case we use AWS SQS from a VPC and have to use a proxy to get to SQS.

**Comment by auvipy** [comment]
I would be looking for a testcase to verify that this change wont introduce regression

**Comment by auvipy** [comment]
please add a testcase for the change

**Comment by aljets** [comment]
@auvipy can you take another look? Thanks!

**Comment by auvipy** [comment]
oh sure. I have re started the CI! thanks for the push!

**Comment by auvipy** [comment]
> @auvipy can you take another look? Thanks!

were you able to make it work in your project?

**Comment by aljets** [comment]
> were you able to make it work in your project using this patch?

Yes, we've actually been using the patch for several years now via a fork for version 4.4.0 on python 2.7 and now for several weeks on version 5.2.2 on python 3.7. Attempting to get it into a release so we can stop using the work :)

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
thanks a lot!

**Pull request merged**
