### PR TITLE
transport/sqs: support mentioning sqs interface endpoint urls, fixes #1136

### LINKED ISSUE #1136: SQS Transport option doesn't support sqs interface endpoint url
If we use awscli, mentioning endpoint-url:
`aws sqs send-message --region us-east-2 --endpoint-url https://sqs.us-east-2.amazonaws.com/ --queue-url https://sqs.us-east-2.amazonaws.com/123456789012/ --message-body "Hello from Amazon SQS."`

In kombu transports, I see an option of https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L500, but how to pass endpoint url here?

### PR DESCRIPTION
**Pull request by iamsudip**
Please guide me how to enable support for this. I guess I have missed it in the documentation, not sure though. But I couldn't find any doc or code where setting endpoint-url is supported.

Please refer to this issue #1136

### CODE REVIEW

**Comment by georgepsarakis** [comment]
@iamsudip could you please add a code snippet that is not working? As far as I can see you can specify the endpoint URL `sqs.us-east-2.amazonaws.com` via the `hostname` parameter.

**Comment by sudip-moengage** [comment]
@georgepsarakis Sure. This is what I have tried.

`tasks.py` looks like this:
```python
BROKER_TRANSPORT_OPTIONS ={'visibility_timeout': 9999, 'region':'us-east-1','polling_interval': 20,'sqs_endpoint_url':'https://sqs.us-east-1.vpce.amazonaws.com'}
app = Celery('tasks', broker='sqs://aws_access_key_id:aws_acess_secret_key+@')
app.conf.update(broker_transport_options=BROKER_TRANSPORT_OPTIONS)

@app.task
def add(x, y):
    print x + y
    return x + y
```

Running the task with:
`celery -A tasks worker --loglevel=info -Q <queue_name> -n https://sqs.us-east-1.vpce.amazonaws.com`

Since the machine where I was running this did not have internet, wasn't able to connect to sqs.
and was stuck here:
```
 
 -------------- celery@https://sqs.us-east-1.vpce.amazonaws.com v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.4.0-1087-aws-x86_64-with-debian-stretch-sid 2019-12-20 14:14:18
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f4f6d270350
- ** ---------- .> transport:   sqs://access_key_id:**@localhost//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> queue_name           exchange=queue_name(direct) key=queue_name
                

[tasks]
  . tasks.add

[2019-12-20 14:14:19,021: WARNING/MainProcess] {u'use_ssl': True}
```

Now when I make changes as mentioned in this PR. This works like this:
```
 
 -------------- celery@https://sqs.us-east-1.vpce.amazonaws.com v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.4.0-1087-aws-x86_64-with-debian-stretch-sid 2019-12-20 14:16:55
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f64dc935350
- ** ---------- .> transport:   sqs://access_key:**@localhost//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> queue_name           exchange=queue_name(direct) key=queue_name
                

[tasks]
  . tasks.add

[2019-12-20 14:16:55,571: WARNING/MainProcess] {u'use_ssl': True, u'endpoint_url': 'https://sqs.us-east-1.vpce.amazonaws.com'}
[2019-12-20 14:16:55,735: INFO/MainProcess] Connected to sqs://access_key:**@localhost//
[2019-12-20 14:16:55,759: WARNING/MainProcess] {u'use_ssl': True, u'endpoint_url': 'https://sqs.us-east-1.vpce.amazonaws.com'}
[2019-12-20 14:16:55,892: INFO/MainProcess] celery@https://sqs.us-east-1.vpce.amazonaws.com ready.
```

Note that: We use endpoint url to communicate through endpoint service without internet access, be it internet gateway/nat. So, while testing this out, we didn't have internet access to this instance.

**Comment by iamsudip** [comment]
@georgepsarakis Sure. This is what I have tried.

`tasks.py` looks like this:
```python
BROKER_TRANSPORT_OPTIONS ={'visibility_timeout': 9999, 'region':'us-east-1','polling_interval': 20,'sqs_endpoint_url':'https://sqs.us-east-1.vpce.amazonaws.com'}
app = Celery('tasks', broker='sqs://aws_access_key_id:aws_acess_secret_key+@')
app.conf.update(broker_transport_options=BROKER_TRANSPORT_OPTIONS)

@app.task
def add(x, y):
    print x + y
    return x + y
```

Running the task with:
`celery -A tasks worker --loglevel=info -Q <queue_name> -n https://sqs.us-east-1.vpce.amazonaws.com`

Since the machine where I was running this did not have internet, wasn't able to connect to sqs.
and was stuck here:
```
 
 -------------- celery@https://sqs.us-east-1.vpce.amazonaws.com v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.4.0-1087-aws-x86_64-with-debian-stretch-sid 2019-12-20 14:14:18
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f4f6d270350
- ** ---------- .> transport:   sqs://access_key_id:**@localhost//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> queue_name           exchange=queue_name(direct) key=queue_name
                

[tasks]
  . tasks.add

[2019-12-20 14:14:19,021: WARNING/MainProcess] {u'use_ssl': True}
```

Now when I make changes as mentioned in this PR and run the task with following command:
`celery -A tasks worker --loglevel=info -Q queue_name`

Logs:

```
 
 -------------- celery@https://sqs.us-east-1.vpce.amazonaws.com v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.4.0-1087-aws-x86_64-with-debian-stretch-sid 2019-12-20 14:16:55
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f64dc935350
- ** ---------- .> transport:   sqs://access_key:**@localhost//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> queue_name           exchange=queue_name(direct) key=queue_name
                

[tasks]
  . tasks.add

[2019-12-20 14:16:55,571: WARNING/MainProcess] {u'use_ssl': True, u'endpoint_url': 'https://sqs.us-east-1.vpce.amazonaws.com'}
[2019-12-20 14:16:55,735: INFO/MainProcess] Connected to sqs://access_key:**@localhost//
[2019-12-20 14:16:55,759: WARNING/MainProcess] {u'use_ssl': True, u'endpoint_url': 'https://sqs.us-east-1.vpce.amazonaws.com'}
[2019-12-20 14:16:55,892: INFO/MainProcess] celery@https://sqs.us-east-1.vpce.amazonaws.com ready.
```

Note that: We use endpoint url to communicate through endpoint service without internet access, be it internet gateway/nat. So, while testing this out, we didn't have internet access to this instance.

**Comment by iamsudip** [comment]
I digged more and added a print statement in base transport as following line with print(self.client.__dict__): https://github.com/celery/kombu/blob/master/kombu/transport/virtual/base.py#L907

And running my worker with hostname:
`celery -A tasks worker --loglevel=info -Q queue_name -n sqs.us-east-1.vpce.amazonaws.com`

I still get same output and make a note that kombu is not getting hostname from celery

```python
{'_initial_params': {u'insist': False, u'ssl': False, u'password': secret+', u'port': None, u'transport': 'sqs', u'login_method': None, u'hostname': None, u'userid': access_key', u'virtual_host': None, u'heartbeat': None, u'connect_timeout': 4}, 'failover_strategy': <type 'itertools.cycle'>, 'login_method': None, 'transport_options': {'region': 'us-east-1', 'sqs_endpoint_url': 'https://sqs.us-east-1.vpce.amazonaws.com', 'visibility_timeout': 9999, 'polling_interval': 20}, 'hostname': None, 'userid': access_key', 'insist': False, 'connect_timeout': 4, 'ssl': False, '_failover_strategy': u'round-robin', 'virtual_host': u'/', 'declared_entities': set([]), 'heartbeat': None, 'alt': [], 'password': secret+', 'port': None, 'transport_cls': 'sqs'}
....
 
 -------------- celery@sqs.us-east-1.vpce.amazonaws.com v4.4.0 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.4.0-1087-aws-x86_64-with-debian-stretch-sid 2019-12-20 14:49:04
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7f2f638a8350
- ** ---------- .> transport:   sqs://access_key:**@localhost//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> queue_name           exchange=queue_name(direct) key=queue_name
                

[tasks]
  . tasks.add

[2019-12-20 14:49:04,293: WARNING/MainProcess] {'_initial_params': {u'insist': False, u'ssl': False, u'password': secret+', u'port': None, u'transport': 'sqs', u'login_method': None, u'hostname': None, u'userid': u'access', u'virtual_host': None, u'heartbeat': 120, u'connect_timeout': 4}, 'failover_strategy': <type 'itertools.cycle'>, 'login_method': None, 'transport_options': {'region': 'us-east-1', 'sqs_endpoint_url': 'https://sqs.us-east-1.vpce.amazonaws.com', 'visibility_timeout': 9999, 'polling_interval': 20}, 'hostname': None, 'userid': 'access', 'insist': False, 'connect_timeout': 4, 'ssl': False, '_failover_strategy': u'round-robin', 'virtual_host': u'/', 'declared_entities': set([]), 'heartbeat': 120.0, 'alt': [], 'password': u'secret+', 'port': None, 'transport_cls': 'sqs'}
[2019-12-20 14:49:04,320: WARNING/MainProcess] None
[2019-12-20 14:49:04,320: WARNING/MainProcess] {u'use_ssl': True}

```

What you suggested is correct but I see that celery is not forwarding hostname to kombu.

**Comment by matteius** [comment]
I like the change but I think to gain more acceptance you should add a unit test that shows passing the new config value for the URL vs not passing it that both tests get the expected SQS broker URL in the result (hence no regressions).

**Comment by georgepsarakis** [comment]
@iamsudip could you try the following broker URL:

```python
app = Celery('tasks', broker='sqs://aws_access_key_id:aws_acess_secret_key+@sqs.us-east-1.vpce.amazonaws.com')
```

**Comment by georgepsarakis** [comment]
Adding a note, as a clarification:

> Running the task with hostname parameter:
```celery -A tasks worker --loglevel=info -Q <queue_name> -n https://sqs.us-east-1.vpce.amazonaws.com```

The `hostname` worker command-line option is unrelated to the broker connection hostname and it allows a user to set the node name of a celery worker process. For details see [here](https://docs.celeryproject.org/en/latest/userguide/workers.html) and [here](https://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html#cmdoption-celery-worker-n).

**Comment by iamsudip** [comment]
> ```python
> app = Celery(
>     'tasks', 
>     broker='sqs://aws_access_key_id:aws_acess_secret_key+@sqs.us-east-1.vpce.amazonaws.com'
> )
> ```
Thank you @georgepsarakis. This worked. Closing PR and issue.

**Comment by georgepsarakis** [comment]
Great, glad I could help.

**Pull request closed without merging**
