### PR TITLE
Update Changelog for 4.2.0

### PR DESCRIPTION
**Pull request by AlexHill**
I've gone through the commits since the last tag and added them, grouping the minor tweaks/fixups and doc changes. I think I've got everything.

Incidentally I've left a question in #689 but that needn't prevent release.

### CODE REVIEW

**Comment by arcivanov** [comment]
#689 is answered in thread.

**Comment by thedrow** [comment]
@auvipy Can you manage the release process?

**Comment by thedrow** [comment]
@auvipy Please create a PGP key to sign the release.
Ping me on twitter if you need help figuring out how the release process goes.

**Comment by auvipy** [comment]
beside releasing 4.2 it is also necessary to change async to asynchronous in celery too

**Comment by auvipy** [comment]
OK

**Pull request merged**
