### PR TITLE
Handle Access Denied Exception in basic_ack Method

### PR DESCRIPTION
**Pull request by flolas**
This change enhances the error handling within the system by specifically addressing the situation where access to an AWS queue is denied.

fixes: https://github.com/celery/kombu/issues/1768

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please rebase it?

**Comment by flolas** [comment]
@auvipy done

**Review by auvipy — CHANGES_REQUESTED** [review]
we got a lint error remaining. can you check and fix it please?

**Comment by flolas** [comment]
@auvipy lint test ok

**Review by auvipy — APPROVED** [review]

**Pull request merged**
