### PR TITLE
fix typing flake8

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by auvipy** [comment]
@Kludex aren't the pre-commit not recognizing future annotation imports? is it possible to configure CI?

**Comment by Kludex** [comment]
I didn't understand the question. Based on what are you asking that? What is this PR doing exactly? 🤔

**Comment by Kludex** [comment]
Need to add `--py39-plus` I guess? https://github.com/asottile/pyupgrade#pep-585-typing-rewrites

**Comment by Kludex** [comment]
Hold on... I didn't get it. What's wrong with the changes on the pre-commit? 🤔 The previous type annotation looks fine...

**Comment by auvipy** [comment]
yes

**Comment by Kludex** [comment]
By previous I mean the current master branch has the right type annotation. 🤔

**Comment by auvipy** [comment]
this was right what you are talking, https://github.com/celery/kombu/commit/1a7b9c490ba9a8ab0daa3dbecb22908799d9bfc7 right?

**Comment by Kludex** [comment]
I'm not understanding, sorry.

There are two commits on the `matcher.py` file:
- Mine: https://github.com/celery/kombu/commit/1a7b9c490ba9a8ab0daa3dbecb22908799d9bfc7
- Pre-commit auto-fixes from yesterday: https://github.com/celery/kombu/commit/008b8f78cdc2bf2e8410f7b33800285a10a2c770

I don't understand what triggered pre-commit CI for that file yesterday, but the annotation it provides is correct.

The replacement below is just fine:
```
-        self._matchers: Dict[str, MatcherFunction] = {}
-        self._default_matcher: Optional[MatcherFunction] = None
+        self._matchers: dict[str, MatcherFunction] = {}
+        self._default_matcher: MatcherFunction | None = None
```
The only problem is that types like `Optional`, `Dict`, etc. were not removed from this file.

You can use the `dict` notation instead of `Dict` and `|` (pipe) instead of `Optional` if you're using `__future__.annotations`.

**Review by Kludex — APPROVED** [review]

**Pull request merged**
