### PR TITLE
Added expiration time for each publishing message

### PR DESCRIPTION
**Pull request by andronat**

### CODE REVIEW

**Comment by ask** [comment]
Thanks! We should probably convert float seconds to milliseconds here, as that's what is usually used in Python.

**Comment by andronat** [comment]
OK, I am on it.

**Comment by andronat** [comment]
Travis fails but I think it is not due to my changes

**Comment by andronat** [comment]
Any news on the subject?

**Comment by ask** [comment]
Thanks! Merged into master and 3.0

**Pull request merged**
