### PR TITLE
update

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by freyes** [comment]
Hi, we are getting build failures, because the dependency defined as `pytz>dev`, is there any chance to cut a new maintenance release (e.g. v5.2.5)?

```
Collecting kombu==5.2.4
Downloading kombu-5.2.4.tar.gz (423 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.4/423.4 kB 18.2 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [5 lines of output]
/root/snap/charmcraft/common/tmprjgh9ibv/lib/python3.8/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
warnings.warn(msg, warning_class)
error in kombu setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
pytz>dev
^
[end of output]
```

**Comment by auvipy** [comment]
I will release 5.3b3 soon

**Comment by Nusnus** [comment]
> I will release 5.3b3 soon

Can you try checking the CI failures first please 🙏? @auvipy

**Comment by auvipy** [comment]
those are related to some packages like uamqp which we dont use directly

**Pull request merged**
