### PR TITLE
do_close_self after setting connection to None will not close previou…

### PR DESCRIPTION
**Pull request by mainred**
…s connection

### CODE REVIEW

**Comment by mainred** [comment]
If the connection still alive, it may 1. be a waste of resource, 2. receive messages from the MQ server without being noticed by the client, which is very dangerous side effect.

**Comment by thedrow** [comment]
I'm not sure about this one.
@ask @malinoff What do you guys think?

**Comment by malinoff** [comment]
+1, but I don't know about why this was originally written in this way - I'd ask @ask about that.

**Comment by MrTomWhite** [comment]
>"If the connection still alive, it may 1. be a waste of resource, 2. receive messages from the MQ server without being noticed by the client, which has a very dangerous side effect."

@mainred: Could we add some automated tests to validate these two invariants? When we have that testing and the build + tests are passing it's probably safe to merge and close the PR. :sunglasses:

**Comment by mainred** [comment]
@MrTomWhite , thank you for your recommendation, I'll try to add such tests later.

**Comment by ask** [comment]
AMQP close operation is actually synchronous, so client sends close, and then waits for close_ok, which means all sorts of things can happen, or not happen, between those two steps.

Using collect here is probably safe for now, we may look into properly handling the synchronous close, but it's rather tricky.

**Comment by mainred** [comment]
@ask , may I get the kombu version that will fix this bug?   Thank you very much.

**Comment by ask** [comment]
It's in the master branch (to be kombu 4.0)

**Pull request closed without merging**
