### PR TITLE
Issue #1019 Fix redis transport socket timeout

### LINKED ISSUE #1019: "Error 110 while writing to socket. Connection timed out." With kombu 4.4.0/4.5.0 and redis 3.2.0/3.2.1
I was previously on kombu 4.3.0 and redis 2.10.6, and after upgrading to kombu 4.4.0/4.5.0 and redis 3.2.0/3.2.1 I noticed a new issue on my Django REST endpoints:

Error 110 while writing to socket. Connection timed out.

These endpoints never had any issues before and this issue popped up only once since I upgraded, but happened on both endpoints simultaneously 

Edit: Bug still there in most recent versions of the libraries (celery 4.3.0, kombu 4.5.0, redis 3.2.1)
(I also had the bug when just upgrading kombu/redis and keeping celery at 4.2.2)
Bug is not there in celery 4.2.2, kombu 4.3.0, redis 2.10.6

```
2019-05-21T07:51:02.022118+00:00 app[worker.1]: [2019-05-21 07:51:02,021: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (0/20) now.
2019-05-21T07:51:02.024750+00:00 app[worker.1]: [2019-05-21 07:51:02,024: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (1/20) in 1.00 second.
2019-05-21T07:51:03.028332+00:00 app[worker.1]: [2019-05-21 07:51:03,028: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (2/20) in 1.00 second.
2019-05-21T07:51:04.032513+00:00 app[worker.1]: [2019-05-21 07:51:04,032: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (3/20) in 1.00 second.
2019-05-21T07:51:05.037741+00:00 app[worker.1]: [2019-05-21 07:51:05,037: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (4/20) in 1.00 second.
2019-05-21T07:51:06.041513+00:00 app[worker.1]: [2019-05-21 07:51:06,041: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (5/20) in 1.00 second.
2019-05-21T07:51:07.045367+00:00 app[worker.1]: [2019-05-21 07:51:07,045: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (6/20) in 1.00 second.
2019-05-21T07:51:08.048339+00:00 app[worker.1]: [2019-05-21 07:51:08,048: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (7/20) in 1.00 second.
2019-05-21T07:51:09.052390+00:00 app[worker.1]: [2019-05-21 07:51:09,052: ERROR/ForkPoolWorker-5] Connection to Redis lost: Retry (8/20) in 1.00 second.
```

### PR DESCRIPTION
**Pull request by kmctown**
Patch from @jschwartzentruber https://github.com/celery/kombu/issues/1019#issuecomment-535157400

Fixes #1019

Wanted to get the ball rolling.

I've got my branch running in a staging environment and can report that it is working well for me. Let me know if there's anything else I can do to help.  cc: @thedrow

### CODE REVIEW

**Comment by auvipy** [comment]
can you check the failing test?

**Comment by auvipy** [comment]
not_found.append(kall)

        if not_found:

            raise AssertionError(

                '%r not all found in call list' % (tuple(not_found),)

>           ) from cause

E           AssertionError: ('', (10, <Mock name='cycle.maybe_restore_messages' id='140344217034256'>), {}) not all found in call list

/opt/python/3.6.7/lib/python3.6/unittest/mock.py:860: AssertionError

**Comment by kmctown** [comment]
> ```
>  not_found.append(kall)
> 
>     if not_found:
> 
>         raise AssertionError(
> 
>             '%r not all found in call list' % (tuple(not_found),)
> ```
> 
> > ```
> >       ) from cause
> > ```
> 
> E AssertionError: ('', (10, ), {}) not all found in call list
> 
> /opt/python/3.6.7/lib/python3.6/unittest/mock.py:860: AssertionError

Thanks. Looking into it...

**Comment by kmctown** [comment]
Great, thanks. That one doesn't look related. Stepping through the code, I don't see where it overlaps with these changes.

**Comment by thedrow** [comment]
We do need to bump the minimum py-redis version though.

**Comment by kmctown** [comment]
> We do need to bump the minimum py-redis version though.

Good call. Bumped to `3.3.11`.

**Comment by ppbdrinker** [comment]
Can we have a release for this beauty please?

**Comment by kmctown** [comment]
Have an update: it seems to have mostly fixed it but I am still getting some occasional broken pipes, so we are not out of the woods yet. It is greatly reduced, though, at least on my workload. I think the 30 timeout might be too high, and we might want 20-25 per @andymccurdy recommendation over on redis-py. Seems like the best solution is to make the configurable `broker_transport_options` update to control `health_check_interval` and reduce the default to `20` or `25`.

**Comment by andymccurdy** [comment]
The `health_check_interval` should definitely be configurable. It's going to vary based on the running environment. If the Redis server or other network appliances between the client and server are configured with timeouts, the user will want to set this value to something less than the min of all of those.

**Comment by auvipy** [comment]
> Can we have a release for this beauty please?

new kombu and celery RC release is due in next 2/3 days

**Comment by thedrow** [comment]
@kmctown Care to open an issue about that? I'll handle it.

**Comment by ppbdrinker** [comment]
> 10 days ago
> new kombu and celery RC release is due in next 2/3 days

Any news?

**Comment by Ashish-Bansal** [comment]
I tried using the latest package it didn't seem to reduce error rate for me in the production. I tried to investigate it. With the health check enabled, it should be sending the PING call to the server to get PONG reply.

```
redis-cli monitor | ag PING
```

^but I don't get expected output from it after every 30 seconds. So, for me health checks ain't really working.

I checked this PR and found that we are calling check_health on the client.

https://github.com/andymccurdy/redis-py/blob/29f4aa43aec50ae0e28df4d3fadfcb17cebe2a2f/redis/client.py#L3193

In redis-py's code, `conn.health_check_interval` is 0 by default. So, it won't actually send the ping. 

So, I think we also need to set `health_check_interval` parameter before calling that function. Anything less than 30(our hardcoded value) should work. 

Also I cannot pass `health_check_interval` into `broker_transport_options` because of hardcoded connection parameters in the kombu https://github.com/celery/kombu/blob/8276480e248d76bf852d89f70647c718ffc01e2a/kombu/transport/redis.py#L895

I believe kombu should allow passing params to the underlying transport blindly but may be there were reasons why it wasn't done in that way.

Anyway, I guess for the time being, I'll try to do money-patching.

**Comment by auvipy** [comment]
did you try celery==4.4.0rc4?

**Comment by Ashish-Bansal** [comment]
@auvipy So you mean we are passing `health_check_interval` in `celery==4.4.0rc4` ? 

I think I did try it but still let me check once again.

**Comment by Ashish-Bansal** [comment]
Alright I just tried using `celery==4.4.0rc4`, it's not working. 

By setting `client.connection.health_check_interval = 5` in kombu, I'm able to see ping messages.

**Comment by auvipy** [comment]
are you up for any fix as PR?

**Comment by Ashish-Bansal** [comment]
> are you up for any fix as PR?

Hm, sure.

**Pull request merged**
