### PR TITLE
Revert "Revert "Revert "Use SIMEMBERS instead of SMEMBERS to check for queue (redis broker)"""

### PR DESCRIPTION
**Pull request by auvipy**
Reverts celery/kombu#1068

### CODE REVIEW

**Comment by lpsinger** [comment]
What version of kombu should I try this with?

**Comment by auvipy** [comment]
master

**Comment by lpsinger** [comment]
Oh, of course. I meant, which version of Celery should I try this with?

**Comment by auvipy** [comment]
celery master

**Comment by lpsinger** [comment]
I installed celery from master and kombu from this branch. Here's my test app:

```
$ cat tasks_min.py 
from celery import Celery

app = Celery('hello', broker='redis://')
app.conf['result_backend'] = app.conf.broker_url

@app.task(shared=False, ignore=True)
def allhi():
    print('all hi!')
```

I started a worker and then a shell with `celery -A tasks_min shell`. The expression `app.control.inspect().stats()` still returns None. However, when I executed that expression, I also got a traceback in the worker. Here's the worker output:

```
$ celery -A tasks_min worker --loglevel INFO -n worker1
 
 -------------- celery@worker1 v4.4.0rc3 (cliffs)
---- **** ----- 
--- * ***  * -- Darwin-18.7.0-x86_64-i386-64bit 2019-11-09 10:03:41
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         hello:0x10c7ac310
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . tasks_min.allhi

[2019-11-09 10:03:41,206: INFO/MainProcess] Connected to redis://localhost:6379//
[2019-11-09 10:03:41,212: INFO/MainProcess] mingle: searching for neighbors
[2019-11-09 10:03:42,233: INFO/MainProcess] mingle: all alone
[2019-11-09 10:03:42,245: INFO/MainProcess] celery@worker1 ready.
[2019-11-09 10:03:49,319: ERROR/MainProcess] Control command error: OperationalError("\nCannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.\nProbably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.\n")
Traceback (most recent call last):
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/connection.py", line 518, in _ensured
    return fun(*args, **kwargs)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/transport/virtual/exchange.py", line 70, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/transport/redis.py", line 877, in _lookup
    exchange, redis_key))
kombu.exceptions.InconsistencyError: 
Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/foo/lib/python3.7/site-packages/celery/worker/pidbox.py", line 46, in on_message
    self.node.handle_message(body, message)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/pidbox.py", line 145, in handle_message
    return self.dispatch(**body)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/pidbox.py", line 115, in dispatch
    ticket=ticket)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/pidbox.py", line 151, in reply
    serializer=self.mailbox.serializer)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/pidbox.py", line 285, in _publish_reply
    **opts
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/messaging.py", line 181, in publish
    exchange_name, declare,
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/connection.py", line 551, in _ensured
    errback and errback(exc, 0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/connection.py", line 444, in _reraise_as_library_errors
    sys.exc_info()[2])
  File "/private/tmp/foo/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/connection.py", line 439, in _reraise_as_library_errors
    yield
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/connection.py", line 518, in _ensured
    return fun(*args, **kwargs)
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/messaging.py", line 203, in _publish
    mandatory=mandatory, immediate=immediate,
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 605, in basic_publish
    message, exchange, routing_key, **kwargs
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/transport/virtual/exchange.py", line 70, in deliver
    for queue in _lookup(exchange, routing_key):
  File "/private/tmp/foo/lib/python3.7/site-packages/kombu/transport/redis.py", line 877, in _lookup
    exchange, redis_key))
kombu.exceptions.OperationalError: 
Cannot route message for exchange 'reply.celery.pidbox': Table empty or key no longer exists.
Probably the key ('_kombu.binding.reply.celery.pidbox') has been removed from the Redis database.
```

**Comment by auvipy** [comment]
Recent feedback from users showed this error was fixed!

**Comment by auvipy** [comment]
check this issue

**Pull request merged**
