### PR TITLE
fix azure service bus isinstance checks when None

### LINKED ISSUE #2045: Azure servicebus transport has hidden dependency on azure-identity package
The azure-servicebus transport depends on azure-identity package, even though it is not listed:

https://github.com/celery/kombu/blob/d620132ecee40fc021f7a78750dfe01331e8a8c0/requirements/extras/azureservicebus.txt#L1

It looks like the code intends for it to be optional:

https://github.com/celery/kombu/blob/d620132ecee40fc021f7a78750dfe01331e8a8c0/kombu/transport/azureservicebus.py#L72-L77

But of course it crashes here when (effectively) calling `isinstance(..., None)`

https://github.com/celery/kombu/blob/d620132ecee40fc021f7a78750dfe01331e8a8c0/kombu/transport/azureservicebus.py#L140-L146

```sh
File "/app/.venv/lib/python3.9/site-packages/kombu/transport/azureservicebus.py", line 144, in _try_parse_connection_string
    if (isinstance(self._credential, DefaultAzureCredential) or
TypeError: isinstance() arg 2 must be a type or tuple of types
```

This problem was introduced in ~#1641~ #1801

### PR DESCRIPTION
**Pull request by jasonwbarnett**
Fixes #2045 and #1947

### CODE REVIEW

**Review by Nusnus — APPROVED** [review]
Thanks for the quick fix!

Just fix the lint issue and we can merge 🚀

```console
pyupgrade................................................................Passed
autoflake................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

kombu/transport/azureservicebus.py:144:80: E501 line too long (109 > 79 characters)
kombu/transport/azureservicebus.py:145:80: E501 line too long (111 > 79 characters)
kombu/transport/azureservicebus.py:146:16: E111 indentation is not a multiple of 4
kombu/transport/azureservicebus.py:146:16: E117 over-indented

Strip unnecessary `# noqa`s..............................................Passed
check for merge conflicts................................................Passed
check toml...........................................(no files to check)Skipped
check yaml...............................................................Passed
mixed line ending........................................................Passed
isort....................................................................Passed
```

**Review by auvipy — CHANGES_REQUESTED** [review]
please fix the lint errors

**Comment by jasonwbarnett** [comment]
@Nusnus @auvipy done

**Review by Nusnus — APPROVED** [review]
Thanks!

**Pull request merged**
