### PR TITLE
Deprecate pytz and use zoneinfo

### PR DESCRIPTION
**Pull request by max-muoto**
Putting out this PR to unblock deprecating pytz in Celery https://github.com/celery/celery/pull/8159.

Fixes https://github.com/celery/kombu/issues/1681

### CODE REVIEW

**Comment by max-muoto** [comment]
CC: @auvipy

**Comment by auvipy** [comment]
I restarted the build

**Comment by max-muoto** [comment]
Should be fixed now @auvipy had to put #noqa to stop flake from complaining if the backports import doesn't get used.

**Comment by max-muoto** [comment]
@auvipy If you want to try again, I think it was complaining due to the backports import being unused in 3.9+.

**Comment by auvipy** [comment]
I have to check that. lets ignore it for now and focus on pytz to zoneinfo only for now.

**Comment by max-muoto** [comment]
> I have to check that. lets ignore it for now and focus on pytz to zoneinfo only for now.

Okay, let me know if I need to do anything else.

**Review by auvipy — APPROVED** [review]

**Review by auvipy — APPROVED** [review]

**Pull request merged**
