### PR TITLE
Allow setting boto3.sqs.create_queue Attributes via transport_options

### LINKED ISSUE #958: Kombu cannot create SQS queues with server-side encryption turned on
We need to configure queues to use server-side encryption when the queues are automatically created by Kombu. This can be done by setting the `KmsMasterKeyId ` and `KmsDataKeyReusePeriodSeconds` keys of the Attributes `boto3 sqs.create_queue ` parameter.

Having a way to set arbitrary Attributes values as new features are added to SQS would be nice.

### PR DESCRIPTION
**Pull request by hfern**
This is useful for setting encryption options on AWS SQS queue creation. 

This implements a general solution, when new features are added to queues, clients using Kombu can just specify additional transport_options.

Fixes #958

### CODE REVIEW

**Comment by hfern** [comment]
Tagging @auvipy since they appear to be on several PR reviews.

**Comment by auvipy** [comment]
which issue is this addressing?

**Comment by thedrow** [comment]
This looks great but requires documentation.

**Comment by hfern** [comment]
@auvipy I've just written an issue for this -- #958.

**Comment by hfern** [comment]
@thedrow I've added some docs --

image

And I fixed a url rendering wrong --

image

**Pull request merged**
