### PR TITLE
azure service bus: add managed identity support

### PR DESCRIPTION
**Pull request by jasonwbarnett**
This is a work in progress. I still need to add a bunch of unit tests.

edit 1: I spent a bunch of time trying to get the unit tests to work and failed in my efforts. I have been running this code in production since this PR was originally opened (Feb 2023).

### CODE REVIEW

**Comment by nattyg93** [comment]
@jasonwbarnett We'd love to use this when it's complete, any chance you've found time to complete this?

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please re-base this?

**Comment by jasonwbarnett** [comment]
> can you please re-base this?

done 👍

**Comment by Nusnus** [comment]
Another rebase is required, some fixes to the linting were pushed to `main` which might be relevant here.

Ping me when you rebase and if you confirm the PR is ready I'll review it quickly @jasonwbarnett

**Comment by jasonwbarnett** [comment]
@Nusnus blindly rebased and pushed just now.

**Review by Nusnus — APPROVED** [review]
LGTM

**Comment by Nusnus** [comment]
@auvipy Notice he edited the original PR message:
> edit 1: I spent a bunch of time trying to get the unit tests to work and failed in my efforts. I have been running this code in production since this PR was originally opened (Feb 2023).

**Comment by Nusnus** [comment]
Merged.
We'll also release 5.3.2 soon so it will include this fix.

@nattyg93 @marnikow FYI

**Comment by auvipy** [comment]
the PR had some issues so we received another PR to address them.

**Pull request merged**
