### PR TITLE
Bring back some of the redis enhancements

### PR DESCRIPTION
**Pull request by matteius**
This doesn't change the implementation of lookup as the old PRs did, but I want to bring back the changes I made to the test harness and to making the code in the redis transport more English readable logic.   This build may fail initially, need to see what the test runners output looks like.

### CODE REVIEW

**Comment by auvipy** [comment]
I will take more time before merging this time. thanks for picking it again.

**Comment by auvipy** [comment]
I will take more time before merging this time. thanks for picking it again.

**Comment by matteius** [comment]
Weird that Travis CI choked on py2 build for something unrelated to these changes:
t/unit/transport/test_qpid.py::test_Transport_verify_runtime_environment.test_raises_exception_for_Python3 ✓75% ███████▌  
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

**Comment by auvipy** [comment]
network issue. i restarted the build

**Comment by matteius** [comment]
@auvipy Can you restart it again, it passed in Travis CI but never ran linting step.  For Appveyor, python2.7 build issue, we should just remove support for Appveyor python 2.7 builds at this point right since py2 is EOL on Jan 1st?

**Comment by matteius** [comment]
I re-forked my kombu repository and will re-make this PR from the branch that I have, is a single commit.

**Pull request closed without merging**
