### PR TITLE
Use fastuuid on CPython>=3.5

### PR DESCRIPTION
**Pull request by thedrow**
Use FastUUID when possible.
FastUUID provides bindings to Rust's UUID library.

It is much faster and I wrote the bindings so I know they are production ready.

### CODE REVIEW

**Comment by auvipy** [comment]
restarted the failing builds

**Comment by thedrow** [comment]
I forgot to mention the library is only available on Linux for now...

**Comment by thedrow** [comment]
Something is wrong with the wheel. I'll try figuring it out on Sunday.

**Comment by thedrow** [comment]
Ok I thought the build environment is the problem but apparently it's because the pip version inside the virtualenv that tox creates is too old.
I'll fix that real quick.

**Comment by yun-gao** [comment]
Hi we are using centOS and AWS Linux, and when we try to install Celery which depends on Kombu, there is no correct fastuuid for us.

**Comment by auvipy** [comment]
it's reverted, try kombu 4.6.3

**Comment by yun-gao** [comment]
It's fixed! Thanks!

**Pull request merged**
