### PR TITLE
Fixing sqs drain_events issues

### LINKED ISSUE #694: SQS Channel doesn't support 'callback' kwarg
SQS Channel doesn't seem to support the 'callback' kwarg.  
```
  File "/Users/mich9038/Git/cloud-daemon/scripts/../cloud_daemon/__init__.py", line 44, in run
    connection.drain_events()
  File "/Users/mich9038/.pyenv/versions/cloud-daemon/lib/python3.6/site-packages/kombu/connection.py", line 301, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/Users/mich9038/.pyenv/versions/cloud-daemon/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 961, in drain_events
    get(self._deliver, timeout=timeout)
  File "/Users/mich9038/.pyenv/versions/cloud-daemon/lib/python3.6/site-packages/kombu/utils/scheduling.py", line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/Users/mich9038/.pyenv/versions/cloud-daemon/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 999, in _drain_channel
    return channel.drain_events(callback=callback, timeout=timeout)
TypeError: drain_events() got an unexpected keyword argument 'callback'
```

Am I just implementing this transport incorrectly?

https://github.com/celery/kombu/blob/master/kombu/transport/SQS.py#L135

Literally changing to 

```
 def drain_events(self, timeout=None, **kwargs):
```

Allows the SQS transport to function properly.

With code such as this:

```
        jobs_exchange = Exchange(CONFIG.TRANSPORT_EXCHANGE, 'direct', durable=True)
        jobs_queue = Queue(CONFIG.TRANPORT_ROUTING_KEY, exchange=jobs_exchange, routing_key=CONFIG.TRANPORT_ROUTING_KEY)
        with Connection(CONFIG.TRANSPORT_URI, transport='sqs', transport_options={'region': 'us-west-2'}) as connection:
            with connection.Consumer(jobs_queue, callbacks=[self._consume_message]):
                while True:
                    connection.drain_events()

```

Where TRANSPORT_URI is 
```
CONFIG.TRANSPORT_URI = 'sqs://'
```

AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY are set using environment variables.

### PR DESCRIPTION
**Pull request by naemono**
resolves #694

### CODE REVIEW

**Comment by auvipy** [comment]
could you make landscape happy? https://landscape.io/github/celery/kombu/pulls/698

**Comment by naemono** [comment]
How would I go about making landscape happy?  I've not dealt w/ it before.  I know why it's complaining, but I think the fix would be worse than the problem.  Maybe a log.debug using kwargs?

Thanks for any input you can provide @auvipy 
```
def drain_events(self, timeout=None, **kwargs):
Unused argument 'kwargs'
```

**Comment by Sheepzez** [comment]
I'm affected by this, so would like to see it merged! :)

**Comment by Sheepzez** [comment]
@auvipy Would it be possible to release this fix on pip? :)

**Comment by thedrow** [comment]
We're releasing soon.

**Comment by underyx** [comment]
@thedrow how soon? :(

Is it possible to downgrade a package perhaps to get rid of this issue? We wanted to start using celery but this issue is making it impossible.

**Comment by thedrow** [comment]
Please follow https://github.com/celery/celery/issues/4109 for details.
We're working on our spare time on this **for free**.
If you need the newest version as soon as possible, please hire one of us to dedicate our full time for this release.

**Comment by underyx** [comment]
@thedrow thanks for the issue link!

Being a maintainer of a FOSS project myself, I do understand time constraints, and I'm sorry if I sounded entitled, my intention was merely to make sure it's clear that celery with SQS seems _100% broken right now_ (I described this through how we experience it since I can't be fully certain the issue is affecting everyone.)

Where I'm a maintainer we care about such reports, for the health of our user base, and we scramble to fix such issues ASAP; I assumed you might work in a similar manner.

**Comment by thedrow** [comment]
I have no idea about the latest working version with SQS. This has been an outstanding bug for a very long time.
@underyx We care. However, we only got release rights very recently. We did not neglect this project on purpose.

**Pull request merged**
