### PR TITLE
fix brop must in same slot error

### PR DESCRIPTION
**Pull request by yeyong123**
Solve to use redis service in aliyun, Brop in same slot error

### CODE REVIEW

**Comment by matteius** [comment]
This will create a merge conflict with some renaming in:  https://github.com/celery/kombu/pull/1132

**Comment by auvipy** [comment]
> This will create a merge conflict with some renaming in: #1132

that's not a big issue.

**Comment by matteius** [comment]
Not a big issue as long as #1132 gets merged first ;-)

**Comment by auvipy** [comment]
that's not a big priority atm

**Pull request merged**
